name: CMake Build on a Single Platform

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libssl-dev  # 安装 OpenSSL 库

    - name: Configure and build Server
      run: |
        cmake -B build/server -S server -DOPENSSL_ROOT_DIR=/usr/lib/ssl -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        cmake --build build/server

    - name: Configure and build Client
      run: |
        cmake -B build/client -S client -DOPENSSL_ROOT_DIR=/usr/lib/ssl -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        cmake --build build/client

    - name: Run tests
      run: |
        cd build/client  # 或者指向包含测试的项目
        ctest --output-on-failure
