name: CMake Build and Release on a Single Platform

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '6.5.0'  # 使用可用的 Qt 版本
        modules: qtbase,qttools

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libssl-dev  # 安装 OpenSSL 库

    - name: Configure and build Server
      env:
        CMAKE_PREFIX_PATH: ${{ env.QT_INSTALL_PATH }}/lib/cmake
      run: |
        cmake -B build/Server -S Server -DOPENSSL_ROOT_DIR=/usr/lib/ssl -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        cmake --build build/Server

    - name: Configure and build Client
      env:
        CMAKE_PREFIX_PATH: ${{ env.QT_INSTALL_PATH }}/lib/cmake
      run: |
        cmake -B build/Client -S Client -DOPENSSL_ROOT_DIR=/usr/lib/ssl -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        cmake --build build/Client

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-output
        path: |
          build/Server/*.exe
          build/Client/*.exe

