name: CMake Build and Release on a Single Platform

on:
  push:
    tags:
      - 'v*'  # 匹配版本号格式的 tag，例如 v1.0, v1.1 等
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '6.5.0'  # 可用的 Qt 版本
        modules: qtbase,qttools

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libssl-dev  # 安装 OpenSSL 库

    - name: Configure and build Server
      env:
        CMAKE_PREFIX_PATH: ${{ env.QT_INSTALL_PATH }}/lib/cmake
      run: |
        cmake -B build/Server -S Server -DOPENSSL_ROOT_DIR=/usr/lib/ssl -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        cmake --build build/Server --config Release

    - name: Configure and build Client
      env:
        CMAKE_PREFIX_PATH: ${{ env.QT_INSTALL_PATH }}/lib/cmake
      run: |
        cmake -B build/Client -S Client -DOPENSSL_ROOT_DIR=/usr/lib/ssl -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        cmake --build build/Client --config Release

    - name: Upload to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          build/Server/*.exe
          build/Client/*.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

